import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {
        public let blue = Color(.sRGB, red: 54/255, green: 192/255, blue: 233/255, opacity: 1) 
    }
}