import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    // Headings

    // 02

    func textStyleHeadings02Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 64))
    }
}
