import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    // boxShadow

    func shadowBoxShadowXl() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.04), radius: 10, x: 0, y: 10) 
    }

    func shadowBoxShadowXl2() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.08), radius: 25, x: 0, y: 20) 
    }
}