import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension

    // line height

    // heading
    public static let dimensionlineHeightheadingH1 = 76 
    public static let dimensionlineHeightheadingH2 = 68 
    public static let dimensionlineHeightheadingH3 = 60 
    public static let dimensionlineHeightheadingH4 = 52 
    public static let dimensionlineHeightheadingH5 = 44 
    public static let dimensionlineHeightheadingH6 = 36 

    // fontsize

    // heading
    public static let dimensionfontsizeheadingH1 = 72 
    public static let dimensionfontsizeheadingH2 = 64 
    public static let dimensionfontsizeheadingH3 = 56 
    public static let dimensionfontsizeheadingH4 = 48 
    public static let dimensionfontsizeheadingH5 = 40 
    public static let dimensionfontsizeheadingH6 = 32 

    // body
    public static let dimensionfontsizebodyLg = 24 
    public static let dimensionfontsizebodyMd = 20 
    public static let dimensionfontsizebodySm = 16 

    // borderWidth
    public static let dimensionborderWidthSm = 1 
    public static let dimensionborderWidthMd = 2 
    public static let dimensionborderWidthXl = 4 
    public static let dimensionborderWidthLg = 3 

    // borderRadius
    public static let dimensionborderRadiusSm = 4 
    public static let dimensionborderRadiusMd = 8 
    public static let dimensionborderRadiusLg = 12 
    public static let dimensionborderRadiusXl = 30 
    public static let dimensionborderRadiusFull = 9999 

    // fontSize
    public static let dimensionfontSizeH1 = 72 
    public static let dimensionfontSizeH2 = 64 
    public static let dimensionfontSizeH3 = 56 
    public static let dimensionfontSizeH4 = 48 
    public static let dimensionfontSizeH5 = 40 
    public static let dimensionfontSizeH6 = 32 
    public static let dimensionfontSizeXl = 24 
    public static let dimensionfontSizeLg = 20 
    public static let dimensionfontSizeMd = 16 
    public static let dimensionfontSizeSm = 14 
    public static let dimensionfontSizeXs = 12 

    // lineHeight
    public static let dimensionlineHeightH1 = 80 
    public static let dimensionlineHeightH2 = 68 
    public static let dimensionlineHeightH3 = 60 
    public static let dimensionlineHeightH4 = 52 
    public static let dimensionlineHeightH5 = 44 
    public static let dimensionlineHeightH6 = 40 
    public static let dimensionlineHeightXl = 32 
    public static let dimensionlineHeightLg = 28 
    public static let dimensionlineHeightMd = 24 
    public static let dimensionlineHeightSm = 20 
    public static let dimensionlineHeightXs = 16 

    // letterSpacing
    public static let dimensionletterSpacingNormal = 0 
}