import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {
        public let color2 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let pantone380C = Color(.sRGB, red: 219/255, green: 228/255, blue: 66/255, opacity: 1) 
        public let pantone303C = Color(.sRGB, red: 0/255, green: 42/255, blue: 58/255, opacity: 1) 
        public let pantone3265C = Color(.sRGB, red: 0/255, green: 199/255, blue: 177/255, opacity: 1) 
        public let pantone573C = Color(.sRGB, red: 181/255, green: 227/255, blue: 216/255, opacity: 1) 
        public let pantone548C = Color(.sRGB, red: 0/255, green: 61/255, blue: 76/255, opacity: 1) 
        public let pantone7714C = Color(.sRGB, red: 0/255, green: 118/255, blue: 128/255, opacity: 1) 

        // Brand Color

        // Base
        public let brandColorBaseWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let brandColorBaseBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 

        // Neutral
        public let brandColorNeutral50 = Color(.sRGB, red: 242/255, green: 242/255, blue: 242/255, opacity: 1) 
        public let brandColorNeutral100 = Color(.sRGB, red: 229/255, green: 229/255, blue: 229/255, opacity: 1) 
        public let brandColorNeutral150 = Color(.sRGB, red: 217/255, green: 217/255, blue: 217/255, opacity: 1) 
        public let brandColorNeutral200 = Color(.sRGB, red: 204/255, green: 204/255, blue: 204/255, opacity: 1) 
        public let brandColorNeutral250 = Color(.sRGB, red: 191/255, green: 191/255, blue: 191/255, opacity: 1) 
        public let brandColorNeutral300 = Color(.sRGB, red: 178/255, green: 178/255, blue: 178/255, opacity: 1) 
        public let brandColorNeutral350 = Color(.sRGB, red: 166/255, green: 166/255, blue: 166/255, opacity: 1) 
        public let brandColorNeutral400 = Color(.sRGB, red: 153/255, green: 153/255, blue: 153/255, opacity: 1) 
        public let brandColorNeutral500 = Color(.sRGB, red: 128/255, green: 128/255, blue: 128/255, opacity: 1) 
        public let brandColorNeutral550 = Color(.sRGB, red: 115/255, green: 115/255, blue: 115/255, opacity: 1) 
        public let brandColorNeutral600 = Color(.sRGB, red: 102/255, green: 102/255, blue: 102/255, opacity: 1) 
        public let brandColorNeutral650 = Color(.sRGB, red: 89/255, green: 89/255, blue: 89/255, opacity: 1) 
        public let brandColorNeutral700 = Color(.sRGB, red: 77/255, green: 77/255, blue: 77/255, opacity: 1) 
        public let brandColorNeutral750 = Color(.sRGB, red: 64/255, green: 64/255, blue: 64/255, opacity: 1) 
        public let brandColorNeutral800 = Color(.sRGB, red: 51/255, green: 51/255, blue: 51/255, opacity: 1) 
        public let brandColorNeutral850 = Color(.sRGB, red: 38/255, green: 38/255, blue: 38/255, opacity: 1) 
        public let brandColorNeutral900 = Color(.sRGB, red: 26/255, green: 26/255, blue: 26/255, opacity: 1) 
        public let brandColorNeutral950 = Color(.sRGB, red: 13/255, green: 13/255, blue: 13/255, opacity: 1) 

        // Turquoise
        public let brandColorTurquoise50 = Color(.sRGB, red: 235/255, green: 255/255, blue: 252/255, opacity: 1) 
        public let brandColorTurquoise100 = Color(.sRGB, red: 204/255, green: 244/255, blue: 239/255, opacity: 1) 
        public let brandColorTurquoise200 = Color(.sRGB, red: 153/255, green: 233/255, blue: 224/255, opacity: 1) 
        public let brandColorTurquoise300 = Color(.sRGB, red: 102/255, green: 221/255, blue: 208/255, opacity: 1) 
        public let brandColorTurquoise400 = Color(.sRGB, red: 51/255, green: 210/255, blue: 193/255, opacity: 1) 
        public let brandColorTurquoise500 = Color(.sRGB, red: 0/255, green: 199/255, blue: 177/255, opacity: 1) 
        public let brandColorTurquoise600 = Color(.sRGB, red: 0/255, green: 159/255, blue: 142/255, opacity: 1) 
        public let brandColorTurquoise700 = Color(.sRGB, red: 0/255, green: 119/255, blue: 106/255, opacity: 1) 
        public let brandColorTurquoise800 = Color(.sRGB, red: 0/255, green: 80/255, blue: 71/255, opacity: 1) 
        public let brandColorTurquoise900 = Color(.sRGB, red: 0/255, green: 40/255, blue: 35/255, opacity: 1) 

        // Yellow
        public let brandColorYellow50 = Color(.sRGB, red: 254/255, green: 255/255, blue: 235/255, opacity: 1) 
        public let brandColorYellow100 = Color(.sRGB, red: 248/255, green: 250/255, blue: 217/255, opacity: 1) 
        public let brandColorYellow200 = Color(.sRGB, red: 241/255, green: 244/255, blue: 179/255, opacity: 1) 
        public let brandColorYellow300 = Color(.sRGB, red: 233/255, green: 239/255, blue: 142/255, opacity: 1) 
        public let brandColorYellow400 = Color(.sRGB, red: 226/255, green: 233/255, blue: 104/255, opacity: 1) 
        public let brandColorYellow500 = Color(.sRGB, red: 219/255, green: 228/255, blue: 66/255, opacity: 1) 
        public let brandColorYellow600 = Color(.sRGB, red: 175/255, green: 182/255, blue: 53/255, opacity: 1) 
        public let brandColorYellow700 = Color(.sRGB, red: 131/255, green: 137/255, blue: 40/255, opacity: 1) 
        public let brandColorYellow800 = Color(.sRGB, red: 88/255, green: 91/255, blue: 26/255, opacity: 1) 
        public let brandColorYellow900 = Color(.sRGB, red: 44/255, green: 46/255, blue: 13/255, opacity: 1) 

        // Navy
        public let brandColorNavy50 = Color(.sRGB, red: 235/255, green: 240/255, blue: 242/255, opacity: 1) 
        public let brandColorNavy100 = Color(.sRGB, red: 204/255, green: 212/255, blue: 216/255, opacity: 1) 
        public let brandColorNavy200 = Color(.sRGB, red: 153/255, green: 170/255, blue: 176/255, opacity: 1) 
        public let brandColorNavy300 = Color(.sRGB, red: 102/255, green: 127/255, blue: 137/255, opacity: 1) 
        public let brandColorNavy400 = Color(.sRGB, red: 51/255, green: 85/255, blue: 97/255, opacity: 1) 
        public let brandColorNavy500 = Color(.sRGB, red: 0/255, green: 42/255, blue: 58/255, opacity: 1) 
        public let brandColorNavy600 = Color(.sRGB, red: 0/255, green: 34/255, blue: 46/255, opacity: 1) 
        public let brandColorNavy700 = Color(.sRGB, red: 0/255, green: 25/255, blue: 35/255, opacity: 1) 
        public let brandColorNavy800 = Color(.sRGB, red: 0/255, green: 17/255, blue: 23/255, opacity: 1) 
        public let brandColorNavy900 = Color(.sRGB, red: 0/255, green: 8/255, blue: 12/255, opacity: 1) 

        // Mint
        public let brandColorMint50 = Color(.sRGB, red: 250/255, green: 252/255, blue: 250/255, opacity: 1) 
        public let brandColorMint100 = Color(.sRGB, red: 240/255, green: 249/255, blue: 247/255, opacity: 1) 
        public let brandColorMint200 = Color(.sRGB, red: 225/255, green: 244/255, blue: 239/255, opacity: 1) 
        public let brandColorMint300 = Color(.sRGB, red: 211/255, green: 238/255, blue: 232/255, opacity: 1) 
        public let brandColorMint400 = Color(.sRGB, red: 196/255, green: 233/255, blue: 224/255, opacity: 1) 
        public let brandColorMint500 = Color(.sRGB, red: 181/255, green: 227/255, blue: 216/255, opacity: 1) 
        public let brandColorMint600 = Color(.sRGB, red: 145/255, green: 182/255, blue: 173/255, opacity: 1) 
        public let brandColorMint700 = Color(.sRGB, red: 109/255, green: 136/255, blue: 130/255, opacity: 1) 
        public let brandColorMint800 = Color(.sRGB, red: 72/255, green: 91/255, blue: 86/255, opacity: 1) 
        public let brandColorMint900 = Color(.sRGB, red: 36/255, green: 45/255, blue: 43/255, opacity: 1) 

        // Primary
        public let primary50 = Color(.sRGB, red: 235/255, green: 255/255, blue: 252/255, opacity: 1) 
        public let primary100 = Color(.sRGB, red: 204/255, green: 244/255, blue: 239/255, opacity: 1) 
        public let primary200 = Color(.sRGB, red: 153/255, green: 233/255, blue: 224/255, opacity: 1) 
        public let primary300 = Color(.sRGB, red: 102/255, green: 221/255, blue: 208/255, opacity: 1) 
        public let primary400 = Color(.sRGB, red: 51/255, green: 210/255, blue: 193/255, opacity: 1) 
        public let primary500 = Color(.sRGB, red: 0/255, green: 199/255, blue: 177/255, opacity: 1) 
        public let primary600 = Color(.sRGB, red: 0/255, green: 159/255, blue: 142/255, opacity: 1) 
        public let primary700 = Color(.sRGB, red: 0/255, green: 119/255, blue: 106/255, opacity: 1) 
        public let primary800 = Color(.sRGB, red: 0/255, green: 80/255, blue: 71/255, opacity: 1) 
        public let primary900 = Color(.sRGB, red: 0/255, green: 40/255, blue: 35/255, opacity: 1) 
        public let primary502 = Color(.sRGB, red: 235/255, green: 255/255, blue: 252/255, opacity: 1) 

        // Secondary
        public let secondary50 = Color(.sRGB, red: 254/255, green: 255/255, blue: 235/255, opacity: 1) 
        public let secondary100 = Color(.sRGB, red: 248/255, green: 250/255, blue: 217/255, opacity: 1) 
        public let secondary200 = Color(.sRGB, red: 241/255, green: 244/255, blue: 179/255, opacity: 1) 
        public let secondary300 = Color(.sRGB, red: 233/255, green: 239/255, blue: 142/255, opacity: 1) 
        public let secondary400 = Color(.sRGB, red: 226/255, green: 233/255, blue: 104/255, opacity: 1) 
        public let secondary500 = Color(.sRGB, red: 219/255, green: 228/255, blue: 66/255, opacity: 1) 
        public let secondary600 = Color(.sRGB, red: 175/255, green: 182/255, blue: 53/255, opacity: 1) 
        public let secondary700 = Color(.sRGB, red: 131/255, green: 137/255, blue: 40/255, opacity: 1) 
        public let secondary800 = Color(.sRGB, red: 88/255, green: 91/255, blue: 26/255, opacity: 1) 
        public let secondary900 = Color(.sRGB, red: 44/255, green: 46/255, blue: 13/255, opacity: 1) 

        // text
        public let textHeadings = Color(.sRGB, red: 0/255, green: 199/255, blue: 177/255, opacity: 1) 
        public let textBody = Color(.sRGB, red: 153/255, green: 153/255, blue: 153/255, opacity: 1) 

        // surface
        public let surfacePage = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let surfaceGeneralCard = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // icon
        public let iconPrimary = Color(.sRGB, red: 0/255, green: 42/255, blue: 58/255, opacity: 1) 

        // Color

        // turquoise
        public let colorturquoise500 = Color(.sRGB, red: 0/255, green: 199/255, blue: 177/255, opacity: 1) 

        // yellow
        public let coloryellow500 = Color(.sRGB, red: 219/255, green: 228/255, blue: 66/255, opacity: 1) 
        public let coloryellow100 = Color(.sRGB, red: 248/255, green: 250/255, blue: 217/255, opacity: 1) 
        public let coloryellow300 = Color(.sRGB, red: 233/255, green: 239/255, blue: 142/255, opacity: 1) 
        public let coloryellow700 = Color(.sRGB, red: 131/255, green: 137/255, blue: 40/255, opacity: 1) 
        public let coloryellow900 = Color(.sRGB, red: 44/255, green: 46/255, blue: 13/255, opacity: 1) 

        // opacity

        // black
        public let coloropacityblack100 = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.04) 
        public let coloropacityblack200 = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.08) 

        // base
        public let colorbaseWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let colorbaseBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 

        // navy
        public let colornavy500 = Color(.sRGB, red: 0/255, green: 42/255, blue: 58/255, opacity: 1) 

        // neutral
        public let colorneutral50 = Color(.sRGB, red: 242/255, green: 242/255, blue: 242/255, opacity: 1) 
        public let colorneutral100 = Color(.sRGB, red: 221/255, green: 229/255, blue: 237/255, opacity: 1) 

        // Base
        public let baseWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
    }
}